[package]
name = "RsSimpleSessionCostCalculator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
everestrs = { workspace = true }

[build-dependencies]
everestrs-build = { workspace = true  }
